spring:
  application:
    name: member
  profiles:
    active: dev
  config:
    import: optional:configserver:http://movie-config-service-1:8071

management:
  endpoints:
    web:
      exposure:
        include: ['refresh','beans','env']
